//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListenManager.src.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fieldvisibility
    {
        public long ID { get; set; }
        public Nullable<long> ID_Verzeichnis { get; set; }
        public Nullable<bool> Anrede { get; set; }
        public Nullable<bool> Mitgliedsnr { get; set; }
        public Nullable<bool> Vorname { get; set; }
        public Nullable<bool> Name { get; set; }
        public Nullable<bool> Straße { get; set; }
        public Nullable<bool> Plz { get; set; }
        public Nullable<bool> Ort { get; set; }
        public Nullable<bool> Bundesland { get; set; }
        public Nullable<bool> Telefon { get; set; }
        public Nullable<bool> Mobil { get; set; }
        public Nullable<bool> eMail { get; set; }
        public Nullable<bool> Eintrittsdatum { get; set; }
        public Nullable<bool> Geburtsdatum { get; set; }
        public Nullable<bool> IBAN { get; set; }
        public Nullable<bool> BIC { get; set; }
        public Nullable<bool> Kreditinstitut { get; set; }
    
        public virtual Verzeichnis Verzeichnis { get; set; }
    }
}
