//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListenManager.src.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitglied
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mitglied()
        {
            this.Verzeichnis = new HashSet<Verzeichnis>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Mitgliedsnr { get; set; }
        public string Anrede { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string Straße { get; set; }
        public Nullable<long> ID_Ort { get; set; }
        public string Telefon { get; set; }
        public string Mobil { get; set; }
        public string eMail { get; set; }
        public Nullable<System.DateTime> Eintrittsdatum { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public string Kreditinstitut { get; set; }
    
        public virtual Ort Ort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verzeichnis> Verzeichnis { get; set; }
    }
}
