//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListenManager.src.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ort()
        {
            this.Mitglied = new HashSet<Mitglied>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PLZ { get; set; }
        public string Name { get; set; }
        public string Bundesland { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitglied> Mitglied { get; set; }
    }
}
